### ISSUE TITLE
Share target on Android doesn't seem to work

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/bundleviewer.octoprint.org#4]
## Problem

When long-pressing on a link from the forums or Github, I have the option to share it with the bundleviewer, however the URL is not passed through.

## Steps to reproduce

1. Add https://bundleviewer.octoprint.org to the home screen
2. Hold on a link and hit 'share', then select OctoPrint Bundle Viewer.
3. Observe issue with no URL passed to BV.

# System details

Samsung Galaxy S21
One UI version 3.1
Android 11
Chrome 90.0.4430.66

I can grab screenshots of what I'm doing if that is not clear 🙂

**Comment by foosel** [comment]
Totally forgot to reply here. I know. Configuration is there, but for some reason it doesn't work and I haven't yet figured out why. For some reason I don't even see the URL getting handed over in the request generated by the phone.

As far as I understand [the spec](https://w3c.github.io/web-share-target/) it should work like this, but it doesn't and I have so far not been able to find a way to debug it.

**Comment by cp2004** [comment]
I have my phone setup for remote debugging, I can give something a go here, and see what happens.

https://developer.chrome.com/docs/devtools/remote-debugging/

**Comment by cp2004** [comment]
Well that was useful, the furthest I got was indeed confirming it is not passing the URL...

**Comment by foosel** [comment]
Oops, that shouldn't have already gotten closed

**Comment by foosel** [comment]
![Screenshot_20210611-110120_Chrome](https://user-images.githubusercontent.com/83657/121661415-75848b00-caa4-11eb-80fd-21c4e92c981f.jpg)

Turns out this was not due to a wrong manifest after all, but actually [an Android limitation](https://bugs.chromium.org/p/chromium/issues/detail?id=789379). Go figure. Took a while to get the parsing right that I put in as a bit of a sanity check, and now we also have a small debug modal that will display input parameters 😅

Finally fixed :)

**Comment by cp2004** [comment]
👍
